In [2]:
import os
import nibabel as nib
import numpy as np
from pathlib import Path
from totalsegmentator.resampling import change_spacing
import multiprocessing
from tqdm.auto import tqdm

WORKER = 60

In [7]:
path = Path("/data/core-rad/data/tucker/raw/Dataset008-lowres-remapped")
resample = 3.0
folder = "imagesTr"
order = 3
subjects = os.listdir(path / folder)

def load_res_save(sample, order=3): #0 for label
    img_in_orig = nib.load(sample)
    img_in = nib.Nifti1Image(img_in_orig.get_fdata(), img_in_orig.affine)
    img_in_rsp = change_spacing(img_in, [resample, resample, resample], order=order, dtype=np.int32, nr_cpus=1)  
    nib.save(img_in_rsp, sample)
    #return img_in_rsp

def lrs(idx):
    su = subjects[idx]
    file = path / folder / su
    load_res_save(file, order=order)
    
with multiprocessing.Pool(WORKER) as p:
    for i in tqdm(p.imap_unordered(lrs, range(len(subjects))), total=len(subjects)):
        pass

100%|███████████████████████████████████████| 1139/1139 [00:52<00:00, 21.84it/s]


In [9]:
path = Path("/data/core-rad/data/tucker/raw/Dataset008-lowres-remapped")
resample = 3.0
folder = "imagesTs"
order = 3
subjects = os.listdir(path / folder)

def load_res_save(sample, order=3): #1 for label
    img_in_orig = nib.load(sample)
    img_in = nib.Nifti1Image(img_in_orig.get_fdata(), img_in_orig.affine)
    img_in_rsp = change_spacing(img_in, [resample, resample, resample], order=order, dtype=np.int32, nr_cpus=1)  
    nib.save(img_in_rsp, sample)
    #return img_in_rsp

def lrs(idx):
    su = subjects[idx]
    file = path / folder / su
    load_res_save(file, order=order)
    
with multiprocessing.Pool(WORKER) as p:
    for i in tqdm(p.imap_unordered(lrs, range(len(subjects))), total=len(subjects)):
        pass

100%|███████████████████████████████████████████| 89/89 [00:07<00:00, 12.13it/s]


In [10]:
path = Path("/data/core-rad/data/tucker/raw/Dataset008-lowres-remapped")
resample = 3.0
folder = "labelsTr"
order = 0
subjects = os.listdir(path / folder)

def load_res_save(sample, order=3): #1 for label
    img_in_orig = nib.load(sample)
    img_in = nib.Nifti1Image(img_in_orig.get_fdata(), img_in_orig.affine)
    img_in_rsp = change_spacing(img_in, [resample, resample, resample], order=order, dtype=np.int32, nr_cpus=1)  
    nib.save(img_in_rsp, sample)
    #return img_in_rsp

def lrs(idx):
    su = subjects[idx]
    file = path / folder / su
    load_res_save(file, order=order)
    
with multiprocessing.Pool(WORKER) as p:
    for i in tqdm(p.imap_unordered(lrs, range(len(subjects))), total=len(subjects)):
        pass

100%|██████████████████████████████████████| 1139/1139 [00:11<00:00, 100.28it/s]


In [11]:
path = Path("/data/core-rad/data/tucker/raw/Dataset008-lowres-remapped")
resample = 3.0
folder = "labelsTs"
order = 0
subjects = os.listdir(path / folder)

def load_res_save(sample, order=3): #1 for label
    img_in_orig = nib.load(sample)
    img_in = nib.Nifti1Image(img_in_orig.get_fdata(), img_in_orig.affine)
    img_in_rsp = change_spacing(img_in, [resample, resample, resample], order=order, dtype=np.int32, nr_cpus=1)  
    nib.save(img_in_rsp, sample)
    #return img_in_rsp

def lrs(idx):
    su = subjects[idx]
    file = path / folder / su
    load_res_save(file, order=order)
    
with multiprocessing.Pool(WORKER) as p:
    for i in tqdm(p.imap_unordered(lrs, range(len(subjects))), total=len(subjects)):
        pass

100%|███████████████████████████████████████████| 89/89 [00:01<00:00, 69.76it/s]


In [2]:
path2 = Path("/data/core-rad/data/tucker/raw/006-lowres/imagesTs/s0013_0000.nii.gz")
print(nib.load(path2))


<class 'nibabel.nifti1.Nifti1Image'>
data shape (116, 88, 150)
affine:
[[   2.99331474   -0.20043327    0.         -165.02062988]
 [   0.20016693    2.99329686    0.           21.76268005]
 [   0.            0.            3.            2.2342279 ]
 [   0.            0.            0.            1.        ]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 116  88 150   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 3. 3. 3. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax 

In [15]:
path2 = Path("/data/core-rad/data/tucker/raw/006-lowres/imagesTs/s0013_0000.nii.gz")
print(nib.load(path2))


<class 'nibabel.nifti1.Nifti1Image'>
data shape (231, 175, 301)
affine:
[[ 1.49665737e+00 -1.00216635e-01  0.00000000e+00 -1.65020630e+02]
 [ 1.00083463e-01  1.49664843e+00  0.00000000e+00  2.17626801e+01]
 [ 0.00000000e+00  0.00000000e+00  1.50000000e+00  2.23422790e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 231 175 301   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.  1.5 1.5 1.5 1.  1.  1.  1. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_dur

In [14]:
print(erg)


<class 'nibabel.nifti1.Nifti1Image'>
data shape (116, 88, 150)
affine:
[[   2.99331474   -0.20043327    0.         -165.02062988]
 [   0.20016693    2.99329686    0.           21.76268005]
 [   0.            0.            3.            2.2342279 ]
 [   0.            0.            0.            1.        ]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 116  88 150   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 3. 3. 3. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax 